fossasia/accounts.susi.ai

src/components/Auth/DeleteAccount/DeleteAccount.react.js
Fixes issue #195 [Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Final deletion button is red instead of blue.
=> red color for final delete button

src/components/Auth/LoggedIn/LoggedIn.react.js, src/components/Auth/Login/Login.react.js
Fixes #204 
Fixes #200 
Changes: Made the page after login responsive (i.e on decreasing browser size the icons don't overlap).
Surge Deployment Link: http://responsive-design-02.surge.sh/
=> Made the page after login responsive and fixed the card issue with login page

src/components/Auth/Login/Login.react.js
Fixes #250 
Changes: Fixed bug on login page. Now login button will enable only if both email and password field are filled and follow the rules correctly.
Surge Deployment Link: http://stupid-owl.surge.sh/
Earlier
Now
=> Fix bug on login page when password field is empty

src/components/StaticAppBar/StaticAppBar.js
Fixes #253 
Changes: Settings is only shown when logged in
Surge Deployment Link: http://abandoned-camera.surge.sh/
=> Settings is only shown when logged in

src/components/Admin/Admin.css, src/components/Admin/Admin.js, src/components/Admin/ListUser/ListUser.css, src/components/Admin/ListUser/ListUser.js, src/components/StaticAppBar/StaticAppBar.js, src/index.js
Fixes #291 
Changes: 
- Implement a basic Admin page which can only be accessible by users with admin user roles
- Add Admin tab in menu below settings
Surge Deployment Link: https://pr-292-fossasia-susi-accounts.surge.sh
=> Add basic admin page

src/components/Settings/Settings.css, src/components/Settings/Settings.react.js, src/components/StaticAppBar/StaticAppBar.js
Fixes #293 
Changes:
- Link settings in menu to '/settings'
- Add delete account as an option in menu instead of child of settings
Surge Deployment Link: https://pr-297-fossasia-susi-accounts.surge.sh
Before
Now
=> Link settings in menu to settings and add delete account as an option

src/components/Admin/Admin.js
Fixes #305 
Changes: 
- Display permission denied message when server responds with 503 on admin page
Surge Deployment Link: https://pr-306-fossasia-susi-accounts.surge.sh
before:
Now:
=> Display permission denied message when server responds with 503

src/components/Admin/Admin.js, src/components/NotFound/NotFound.react.js
Fixes #311 
Changes: 
- Display 404 error if anyone other than admin tries to access admin route.
- Add top bar to not found page.
Surge Deployment Link: https://pr-312-fossasia-susi-accounts.surge.sh
=> Display 404 error if anyone other than admin tries to access admin route and add top bar to not found page

src/components/Settings/Settings.react.js
Fixes #314 
Changes:  Mobile field should accept only numerical inputs
Surge Deployment Link: https://pr-315-fossasia-susi-accounts.surge.sh
=>  Mobile field should accept only numerical inputs

src/components/Admin/Admin.css, src/components/Admin/Admin.js, src/components/Admin/ListUser/ListUser.css, src/components/Admin/ListUser/ListUser.js, src/components/StaticAppBar/StaticAppBar.js
Fixes #319 
Changes: 
- Pagination on admin tab is not working properly
- Remove SUSI.AI from heading of admin page and change to H2.
- Position of tabs should be left
- Implement card style for tabs similar to admin panel of open event
- Change position of Admin in menu below About
Surge Deployment Link(for Admins): https://pr-320-fossasia-susi-accounts.surge.sh
Test Link(for non Admins/No login required):http://womanly-car.surge.sh/
Implement tab style similar to open event admin panel and remove SUSI.Ai from heading
Before:
Fix issues with pagination
Before:
=> Fix pagination issue and add card style for tabs on admin page

src/components/Admin/ListSkills/ListSkills.js
Fixes #328 
Changes: Allowing admin to change review status of skills.
Test Link: http://sweet-soap.surge.sh/. Choose `Admin` from the dropdown hamburger menu to access admin tab. (Logging in is not required)
The review status will change if you're the admin.
It'll fail if you try to change review status but you're not admin.
=> Allow admin to change review status of skills

src/components/Admin/ListSkills/ListSkills.js
Fixes #340 
Changes: Fixed API call issues by using skill tag instead of skill name
For example, earlier the query parameter `skill` in the API call while changing review status of `Anime Suggestions` Skill was:
`https://api.susi.ai/cms/changeSkillStatus.json?skill=Anime%20Suggestions&otherParameters`
Now, the API call is:
`https://api.susi.ai/cms/changeSkillStatus.json?skill=Anime_Suggestions&otherParameters`, where `Anime_Suggestions` is the `skill_tag` of the Skill
Surge Deployment Link: https://pr-1166-fossasia-susi-skill-cms.surge.sh
=> Fixed API call issues by using skill tag instead of skill name

src/components/StaticAppBar/StaticAppBar.js
Fixes #337 
Changes:
* Add Admin menuitem in Hambuger menu.
Surge Deployment Link: https://pr-351-fossasia-susi-accounts.surge.sh
=> Fixes #337: Add Admin to menu-item

src/components/Auth/Logout.react.js, src/components/StaticAppBar/StaticAppBar.js
Fixes #363 
Persist showAdmin cookie over SUSI.AI subdomains
Surge Deployment Link: Won't reflect the change as the PR is domain specific
NA
=> Fixes #363: Persist showAdmin cookie over SUSI.AI subdomains

src/components/Admin/ListUser/ListUser.js
Fixes #361 
Changes: Removed user role `BOT` from dropdown in Admin Panel. 
Relevant PR on server: https://github.com/fossasia/susi_server/pull/1047
Surge Deployment Link: https://pr-365-fossasia-susi-accounts.surge.sh
=> Removed user role BOT from dropdown in Admin Panel

src/components/Admin/ListSkills/ListSkills.js
Fixes #355 
Changes: Added functionality to change Edit status of any Skill from Admin Panel. This is similar to how the functionality to change review status of any Skill is already implemented.
Corresponding PR on Skill CMS: https://github.com/fossasia/susi_skill_cms/pull/1244
Surge Deployment Link: https://pr-367-fossasia-susi-accounts.surge.sh
=> Added functionality to change edit status of any Skill from Admin panel

src/components/Admin/Admin.js, src/components/Admin/ListSkills/ListSkills.js, src/components/Admin/ListUser/ListUser.js, src/components/Auth/Login/Login.react.js, src/components/StaticAppBar/StaticAppBar.js, src/index.js
Fixes #345 
Fixes #352 
Changes: 
- Add subroutes for different admin tabs
- Implement `showAdmin` cookie during login to check admin status instead of calling API everytime on different components
- This reduces extra API calls and admin panel is loading instantly without 404 in between 
- Temporarily remove permissions tab as it is empty and will re implement it as a subroute like users tab in #334 
Surge Deployment Link: https://pr-353-fossasia-susi-accounts.surge.sh
=> Implement subroutes for admin tabs and minor fixes

src/components/Admin/ListSkills/ListSkills.css
Fixes #350
Changes: Simple css added.
Surge Deployment Link: https://pr-378-fossasia-susi-accounts.surge.sh
=> Fixes #350: Center the circular loader on skills tab

src/components/Admin/ListUser/ListUser.js
Fixes #372 
Changes: Display device info of users on users tab
**To review** Go to page 14 of the table to see live preview of akshat's devices
Surge Deployment Link: https://pr-380-fossasia-susi-accounts.surge.sh
=> Display device info of users on users tab

src/components/Admin/Admin.css
Fixes #387 
Changes: Improved styling of different tab headings in Admin Panel. This was also done to make it similar with the styling done on the Skill CMS Admin Panel.
Surge Deployment Link: https://pr-388-fossasia-susi-accounts.surge.sh
Before:
After:
=> Improved styling of different tab headings in Admin Panel

src/components/Admin/Admin.css, src/components/Admin/Admin.js
Fixes #385 
Changes:
- Implement skills stats on admin panel
- Made users card similar to skills card
Surge Deployment Link: https://pr-390-fossasia-susi-accounts.surge.sh
=> Implement skills stats on admin panel

src/components/Admin/ListUser/ListUser.js
Fixes #395 
Changes: Displayed name of users in Users tab in Admin Panel
NOTE: Can be tested after https://github.com/fossasia/susi_server/pull/1098 is merged.
Corresponding PR on CMS: https://github.com/fossasia/susi_skill_cms/pull/1404
Surge Deployment Link: https://pr-400-fossasia-susi-accounts.surge.sh
=> Displayed name of users in Users tab in Admin Panel

src/components/Admin/ListSkills/ListSkills.js
Fixes #394
Changes: Changed dropdowns to checkbox while changing status of any Skill from Admin panel.
Corresponding PR on CMS: https://github.com/fossasia/susi_skill_cms/pull/1392
Surge Deployment Link: https://pr-408-fossasia-susi-accounts.surge.sh
NOTE: Issue of non-standard blue color is already being taken care in https://github.com/fossasia/accounts.susi.ai/pull/397
=> Changed dropdowns to checkbox while changing status of any Skill from Admin panel

src/components/Admin/ListSkills/ListSkills.js
Fixes #386 
Changes: Added functionality to mark any Skill as Staff Pick from Admin Panel
Corresponding PR on CMS: https://github.com/fossasia/susi_skill_cms/pull/1450
Surge Deployment Link: https://pr-429-fossasia-susi-accounts.surge.sh
=> Added functionality to mark any Skill as Staff Pick from Admin Panel

src/components/Admin/ListUser/ListUser.js
Fixes #430 
Changes: Remove extra padding from search bar
Surge Deployment Link: https://pr-438-fossasia-susi-accounts.surge.sh
Now:
Before:
=> Remove extra padding from search bar

src/components/Admin/ListSkills/ListSkills.css, src/components/Admin/ListSkills/ListSkills.js
Fixes #443 
Changes: Consistent styling in all dialog boxes in Admin Panel.
Corresponding PR on Skill CMS: https://github.com/fossasia/susi_skill_cms/pull/1531
Surge Deployment Link: https://pr-453-fossasia-susi-accounts.surge.sh
Before:
After:
=> Consistent styling in all dialog boxes in Admin Panel

src/components/Admin/ListSkills/ListSkills.js
Fixes #459 
Changes: Added functionality to mark any Skill as System Skill from Admin Panel
Corresponding PR on CMS: https://github.com/fossasia/susi_skill_cms/pull/1569
Surge Deployment Link: https://pr-461-fossasia-susi-accounts.surge.sh
=> Added functionality to mark any Skill as System Skill from Admin Panel

src/components/Auth/ForgotPassword/ForgotPassword.css
Fixes #477 
Changes:
- Decrease padding of forgot password form's container div when the screen size is less then 490px.
Surge Deployment Link: https://pr-478-fossasia-susi-accounts.surge.sh
@anshumanv @akshatnitd @arundhati24 please review this PR.
=> Decrease padding with screen size decrease

src/components/StaticAppBar/StaticAppBar.js
Fixes #471 
Changes:
* Prevent display of cached avatar image
Surge Deployment Link: https://pr-476-fossasia-susi-accounts.surge.sh
=> Fixes #471: Prevent display of cached avatar image

src/components/StaticAppBar/StaticAppBar.css, src/components/StaticAppBar/StaticAppBar.js
Fixes #495 
Changes: Username disappears when screen width is less.
Surge Deployment Link: https://pr-496-fossasia-susi-accounts.surge.sh
=> responsive design added

src/components/Settings/Settings.css
Fixes #509
Due to confusion from https://github.com/fossasia/accounts.susi.ai/pull/479, new PR.
Changes: Align radio buttons in settings to right
Surge Deployment Link: https://pr-509-fossasia-susi-accounts.surge.sh
**Before**
**After**
=> Align Settings Radio Buttons to Right #509

src/components/Settings/Settings.react.js
Fixes #525 
Changes: Disabled added in the button edit theme for light/dark theme
Surge Deployment Link: https://pr-526-fossasia-susi-accounts.surge.sh
=> Edit theme disabled for light/dark

src/components/Auth/ChangePassword/ChangePassword.css, src/components/Auth/ChangePassword/ChangePassword.react.js
Fixes #515 
Changes: 
Elements of password tab remain in proper order even after resizing
Surge Deployment Link: https://pr-518-fossasia-susi-accounts.surge.sh
=> Retain input tags order on resizing

src/components/Settings/Settings.react.js
Fixes #531 
Changes: On decreasing the screen size, the phone number and country code fields stay together now.
- Minor change: Also when the screen size is less, the floating label of the phone number field used to coincide with the text, it is also fixed.
Surge Deployment Link: https://pr-532-fossasia-susi-accounts.surge.sh
=> Phone number and Country code fields now stay together when screen size is decreased.

src/components/Settings/Settings.css, src/components/Settings/Settings.react.js
Fixes #514 
Changes: When screen size is decreased, the radio buttons aren't misaligned in the speech tab of the settings page.
Surge Deployment Link: https://pr-516-fossasia-susi-accounts.surge.sh
@anshumanv @Akshat-Jain @akshatnitd  please review, Thanks!
=> Fixed switch buttons misalignment on decreasing screen size in Speech settings

src/components/Auth/ChangePassword/ChangePassword.react.js
Fixes #540 
Changes: save new password is not enabled when text fields are empty while changing the password on [settings](https://accounts.susi.ai/settings)
Surge Deployment Link: https://pr-541-fossasia-susi-accounts.surge.sh
=> save new password is not enabled when text fields are empty

src/components/Settings/Settings.css
Fixes #543 
Changes: Radio buttons were toggled to right.
Surge Deployment Link: https://pr-556-fossasia-susi-accounts.surge.sh
=> Radio buttons' alignment changed to right

src/components/Auth/ChangePassword/ChangePassword.react.js, src/components/Auth/ResetPassword/ResetPassword.react.js, src/components/Auth/SignUp/SignUp.react.js
Fixes #581 
Changes: As maximum allowed length of password on server side is 64 characters, upper cap for the same has been added.
Surge Deployment Link: https://pr-582-fossasia-susi-accounts.surge.sh
GIF-
=> Maximum limit of allowed password length in password fields added

src/components/Auth/SignUp/SignUp.css, src/components/Auth/SignUp/SignUp.react.js
Fixes #587 
Changes: Added padding between the login button and the footer.
Surge Deployment Link: https://pr-588-fossasia-susi-accounts.surge.sh
=> Added padding in login button

src/components/Auth/ChangePassword/ChangePassword.react.js, src/components/Auth/DeleteAccount/DeleteAccount.react.js
Fixes #584 
Changes: Minimum password length warning removed from where it is not required.
Surge Deployment Link: https://pr-608-fossasia-susi-accounts.surge.sh
GIF-
=> Minimum password length warning removed 

src/components/Auth/ChangePassword/ChangePassword.react.js
Fixes #633 
Changes: Placeholder text changed to `Must be from 6 to 64 characters`
Surge Deployment Link: https://pr-634-fossasia-susi-accounts.surge.sh
=> Placeholer in change password form text changed

src/components/NotFound/NotFound.react.js
Fixes #650 
Changes: 
When logged in,
Surge Deployment Link: https://pr-651-fossasia-susi-accounts.surge.sh
=> NotFound: hide signup and login buttons when the user is logged in.

src/components/Settings/Settings.css
Fixes #600 
Changes: Height of right section and nav-bar on settings page is same.
Surge Deployment Link: https://pr-601-fossasia-susi-accounts.surge.sh
=> Height of nav and the right section is same

src/components/ProtectedRoute/ProtectedRoute.js
Fixes #694 
Changes: Currently, in ProtectedRoute component, when the user is not logged in, it is redirecting to /error-404. Instead, it should display not found for that page.
Surge Deployment Link: https://pr-695-fossasia-susi-accounts.surge.sh
=> ProtectedRoute: prevent unwanted redirect

src/components/Settings/Settings.css
Fixes #589
Changes: The width of the settings list is the same when the width of the window is varied.
Surge Deployment Link: https://pr-606-fossasia-susi-accounts.surge.sh
=> proper responsive on settings page

src/components/Auth/ForgotPassword/ForgotPassword.css, src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #656 
Changes: Currently the forgot password modal is not responsive for small screen devices. But, it should be responsive.
Surge Deployment Link: https://pr-662-fossasia-susi-accounts.surge.sh
=> forgotPassword: modify responsiveness for small screen devices

src/components/Auth/ForgotPassword/ForgotPassword.react.js
Fixes #723 
Changes: Email field clears itself after the cancel button is clicked.
Surge Deployment Link: https://pr-724-fossasia-susi-accounts.surge.sh
=> Email field clears after clicking on cancel

src/components/Settings/Settings.css, src/components/Settings/Settings.react.js
Fixes #720 
Changes: Currently the heights of User Name and Select Avatar on settings page are uneven. It should be even.
Surge Deployment Link: https://pr-720-fossasia-susi-accounts.surge.sh
=> settings: heights of User Name and Select Avatar is evened in same line

src/components/Settings/Settings.css, src/components/Settings/Settings.react.js
Fixes #718 
Changes: Currently the heights of menu and account description on settings page are uneven. It should be even.
Surge Deployment Link: https://pr-719-fossasia-susi-accounts.surge.sh
=> settings: make menu and description heights consistent

src/components/Auth/ChangePassword/ChangePassword.react.js, src/components/Auth/DeleteAccount/DeleteAccount.react.js, src/components/Auth/ForgotPassword/ForgotPassword.react.js, src/components/Auth/Login/Login.react.js, src/components/Auth/ResetPassword/ResetPassword.react.js, src/components/Auth/SignUp/SignUp.react.js, src/components/Auth/VerifyAccount/VerifyAccount.react.js, src/components/Settings/WebChat/WebchatSettings.react.js
Fixes #623 
Changes: Display snackbar instead of modal for alert on:
Surge Deployment Link: https://pr-717-fossasia-susi-accounts.surge.sh
=> display snackbar instead of modal for alert

src/Utils/isMobileView.js, src/components/Admin/ListSkills/ListSkills.js, src/components/Admin/SystemSettings/SystemSettings.js
Fixes #747 
Changes: 
Make the tables in Admin Panel Mobile Responsive.
Made the Skills and System Settings Table Mobile Responsive.
Note: Did not work on User Table as data is not loading.
Surge Deployment Link: https://pr-748-fossasia-susi-accounts.surge.sh
=> Make the tables in Admin Panel Mobile Responsive

src/components/Settings/Settings.react.js
Fixes #734 
Changes: [Add here what changes you made in this Pull Request and if possible provide links referring the changes.]
Increase the width of country code text field in mobile tab in settings.
Surge Deployment Link: https://pr-735-fossasia-susi-accounts.surge.sh
=> Fix UI bug in Mobile tab in Settings
