.travis.yml

First step #4 : Basic .travis.yml additions
Build must be failing write now as no changes have been made to code since import. Before resolving this issue we must get started with code changes first.

added travis.yml

---

.github/ISSUE_TEMPLATE
.github/PULL_REQUEST_TEMPLATE

Fixes #8 
Added a template file in .github directory to provide a basic structure to all the new issues and pull requests

added template for issues and Pull Requests

---

index.html
js/framework.js

First step #7 
Added missing libraries

added missing libraries

---

index.html

part of #7 
Changes: changed search query link of Get JSON data button

Final step to landing page

---

apps/susi/index.html

Fixes issue #17 
Changes: Changed links to files.

changed reference to chat.susi.ai in Chat with SUSI app

---

.travis.yml
utilities/deploy.sh

Fixes #5, First step in auto deployment of gh-pages. 
Next step will be to generate encrypted keys with admin account.

First step in Auto deployment to gh-pages

---

apps/loginpage/js/loginpage.js

Fixes issue #16 
Changes: Updated  login app. Major changes in loginpage.js file

Fixed login to susi app

---

apps/signup/js/signup.js
js/framework.js

Resolves #20, Sign up web page is clear, visible, working
You can test it here : https://jyoth1raditya.github.io/accounts.susi.ai/apps/signup/

Sign up app is working

---

apps/accountpermissions/index.html
apps/accountpermissions/js/app.js

Fixes view permissions application

---

apps/keyRegistration/js/registration.js

Fixes issue #19 
Changes: changed data type and updated the API call.

Fixes key registration app 

---

js/framework.js

Fixes issue #12, #7  
Changes: removed http.getJSON call and added AJAX jsonp call to populate navigation bar.

Broken Navigation bar fixed

---

apps/forgotpassword/js/passwordrecovery.js

Fixes issue#21 
Changes: Updated forgot password app. Major changes in passwordrecovery.js file

Fixes password recovery in susi app

---

apps/consolerule/js/app.js

Fixes issue #23, Console app is functional and working

Working console app

---

apps/resetpass/js/resetpass.js

Fixes Issue #22, Reset password is working as expected.
Changes are made in `resetpass.js`

Fixed reset password to susi app

---

apps/signup/js/signup.js

Fixes issue #40, Signup form is working

fixes bug in signup form

---

.travis.yml

updated travis file for better integration.

updated travis

---

src/App.test.js
src/__tests__/components/ChatApp.js
src/__tests__/components/MessageComposer.js
src/__tests__/components/MessageSection.js
src/__tests__/components/ThreadSection.js
src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js
src/index.js

Fixes issue #62 
-Changes: Added top bar in login and signup page.
sample deployment -> http://hushed-whip.surge.sh/
This is the first step. Will be pushing more to make it look exactly same.

top bar added

---

.travis.yml

Fixes issue #47 
Changes: travis was building development branch which does not exists. Updated travis for master branch

travis enhancement

---

src/components/Auth/ResetPassword/ResetPassword.react.js

fixes #90 
sample deployment -> http://daily-quartz.surge.sh/

option for custom server

---

.gitignore

Fixes issue #96 
Changes: .gitignore file

add package-lock.json to .gitignore

---

src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/Login/Login.react.js
src/index.js

Fixes issue #92 
Changes: refactored reset password to change password.

reset password refactored to change password

---

src/components/Auth/LoggedIn/LoggedIn.css
src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/Auth/Login/Login.react.js
src/index.js

First step of #91.
Changes: If a user logs in with with valid credentials, he/she is redirected to home page.
Surge Deployment Link: http://rebel-voice.surge.sh/

Add user homepage

---

src/components/Auth/Login/Login.react.js

Fixes issue #105 
Changes: added a check in login for finding a token in cookies
Surge Deployment Link: http://rebel-voice.surge.sh/

check cookies for token and load account if present

---

package.json
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/Auth/Login/Login.react.js

Fixes issue #84 
surge deployment -> http://half-blood.surge.sh/
login to your account and from the navigation bar, click on change password.

added option to change password

---

src/components/Auth/ResetPassword/ResetPassword.react.js
src/index.js

Fixes issue #94 
Changes: After merge of this pr, users can be redirected to http://accounts.susi.ai/resetpass/?token=token to allow them to reset their password.
Surge Deployment Link: cannot be tested at surge.
Screenshots :

Reset Password Added

---

src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js

Fixes issue #94 
Changes: functionality of reset password
Surge Deployment Link: http://susi-reset-password.surge.sh/
This is the surge sample deployment link (http://susi-reset-password.surge.sh/). A little drill to check whether reset password is working or not! Also please point out to any bug/error you come across. Go to the above given link and click on forgot password. enter your email id and extract just the token {last 30 characters} from the password reset link. Now append the token to 'http://susi-reset-password.surge.sh/?token='
this is to check if reset password is working or not. 
Thanks!

Changes in Reset Password Functionality

---

src/components/Auth/Login/Login.react.js

Progress on #113 
Changes: Removes option for custom server login from accounts.
surge deployment : http://remove-custom.surge.sh/

Removed option for custom server from login

---

src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/ForgotPassword/ForgotPassword.css
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.css
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.css

Fixes issue #117 
Changes: Added more attributes to app-bar-div to make it stay even when the user scrolls or is viewing the page in a larger frame
Surge Deployment Link: http://fix-appbar.surge.sh/

Fix appbar scrolling bug

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/SignUp/SignUp.react.js

bug fix in error messages while changing password

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js

Fixes issue #113 
Changes: remove option for custom server from forgot password
Surge deployment : honorable-swim.surge.sh

removed custom server option

---

package.json
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes issue #129 
Changes: Removed errors
Surge Deployment Link: http://alleged-oven.surge.sh/

Fixes console 404 not found error

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes issue #132 
Changes: updated hex values
Surge Deployment Link: change-theme.surge.sh

Changed theme

---

deploy.sh

Fixes issue #142 
Changes: 
-  fixed path for deploy_key

Fixes #142 - Wrong path to deploy_key

---

src/components/Auth/VerifyAccount/VerifyAccount.css
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/index.js

account verification link

---

src/components/Auth/LoggedIn/LoggedIn.react.js

added link to browse skills

---

src/components/Settings/WebChat/WebchatSettings.react.js

[WIP] [DNM] settings for each client individually

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js

Fixes issue #155 
Changes: changed http to https

http to https

---

docs/Accounting.md

Removed syntax typo
Fixes issue #161
Screenshot:
https://screenshots.firefox.com/d2yCBfjy4KHDfjTR/github.com

Typo in syntax of accounting.md

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js

Fixes issue #163 
Changes:
* Centered submit buttons on the DeleteAccount component.
* Changed MenuItem text to `Delete Account`
* Some indentation fixes.
Surge Deployment Link: https://accsusi163.surge.sh

Fixes #163: Centered buttons on DeleteAccount component

---

src/components/Auth/ResetPassword/ResetPassword.react.js

Fixes issue #158 
Changes: Add 'Email' as floating text and not as normal text and fixed some indentations too.
Surge Deployment Link: http://accsusi158.surge.sh/

Improve ResetPassword component

---

README.md
docs/Accounting.md
public/index.html
src/actions/API.actions.js
src/actions/History.actions.js
src/components/Auth/LoggedIn/LoggedIn.react.js
src/stores/UserPreferencesStore.js

Fixes issue #155 
Changes: Migrated from http to https.
Surge Deployment Link: https://accsusi155.surge.sh

Fixes #155: Migrate from http to https

---

src/components/Auth/Login/Login.react.js

Fixes #165 
Changes: Refactoring.
Surge Deployment Link: http://accsusi165.surge.sh/

Fixes #165: Removed documented changePassword link and improved indents

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js

Fixes #167 
Changes: Larger paper component to contain all child elements
Surge Deployment Link: http://susiacc167.surge.sh/

Fixes #167: Adjust Paper component to contain all child components

---

src/components/Auth/LoggedIn/LoggedIn.react.js

Fixes issue #171 
Changes: Corrected the typing error in the spelling of delete account.
Surge Deployment Link: http://typing-error.surge.sh/
Before:
After:

Corrected the typing error in the spelling of delete account.

---

.github/ISSUE_TEMPLATE

Fixes #183
Changes: Commenting out suggestions in issue template
EDIT: Fixes #178

Comment out suggestions in issue template

---

.gitignore
src/components/Auth/Login/Login.react.js

Fixes issue #200 
Changes: 
Added style to login div.

Login Page Card Layout Added.

---

.gitignore
src/components/Auth/Login/Login.css

Fixes issue #198
Changes: Modified login.css.

Fixes issue #198

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js

Fixes issue #192 [Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Surge Deployment Link: [Add here the link where you changes can be seen]

Add padding and red color to try again message

---

src/components/Auth/LoggedIn/LoggedIn.css

Fixes issue #193 [Add issue number here. If you do not solve the issue entirely, please change the message e.g. "First steps for issues #IssueNumber]
Changes: 
[Add here what changes were made in this issue and if possible provide links.]
Surge Deployment Link: [Add here the link where you changes can be seen]

Center align icons on home screen

---

src/components/Auth/LoggedIn/LoggedIn.react.js

Fixes issue #190 
Changes:
Combined the change password and delete account under Account settings
Surge Deployment Link: 
http://combine-1.surge.sh/
Before:-
After:-

Combined the change password and delete account under Account settings

---

.github/PULL_REQUEST_TEMPLATE

Fixes #185
Changes: Changed PULL_REQUEST_TEMPLATE to close issues automatically when PR is merged
EDIT: Fixes #179

Close issue automatically when PR is merged

---

src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes #202 
Changes: Added icon images in the menu.
Deployment link : http://icon-fix.surge.sh/

Added icon images in the menu

---

src/components/Auth/Login/Login.react.js

Fixes #205 
Changes: 
[Add here what changes were made in this issue and if possible provide links.]

Improve UI for login page

---

docs/Accounting.md
src/components/Auth/Login/Login.react.js
src/components/NotFound/NotFound.react.js

Fixes #210 
Changes: Fixes the typo and also makes the formatting of the file uniform.

Fixes one typo and improves formatting of Accounting.md file

---

src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #217
Changes: 
Updated Button Style

Fixes Issue #217

---

src/components/Auth/Login/Login.react.js

Fixes #208 
**Changes:** Fixes some typos on the main page.
**Screenshots for the change:**
Current status:
Updated status:

Fixes some typos on the main page

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js

Fixes #215 
Changes: Updated button style

Fixes #215

---

src/components/Auth/Login/Login.react.js

Fixes issue #169 
Changes: 
Implemented a pop-up dialog box when password or email is incorrect.
Surge Deployment Link: http://dialog-box.surge.sh/

Pop-up dialog box implemented when password or email is incorrect

---

src/components/Auth/Footer/Footer.css
src/components/Auth/Footer/Footer.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js

Fixes #221 
Changes: Add Footer
Surge Deployment Link: http://afraid-actor.surge.sh

Add footer

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js

Fixes #223 
Surge Deployment Link: http://defiant-bean.surge.sh/
Before -
After -

Minor UI fixes on login page

---

README.md
docs/Accounting.md
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js

Fixes issue #145 
Fixes issue #180 
Fixes issue #177 
Fixes issue #174 
Fixes issue #173 
Fixes issue #171 
Changes: Displays email Id when logged in.
And fixed multiple small issues.
Surge Deployment Link: http://fixes.surge.sh/

Added Email Id in the Logged in window and fixed multiple small issues

---

package.json
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Surge Deployment Link: passwrod-strenght.surge.sh

Adding a strength bar to the password field in the sign up #228

---

src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Surge Deployment Link:  skills-link.surge.sh

Give a link to skills page in the menu bar #231

---

src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Surge Deployment Link: http://icon-login.surge.sh/

No icon for email and password text fields #226

---

commitStyle.md

Fixes #213 
Changes: Added commitStyle.md

Fixes issue #213

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js
src/index.js

Fixes #243 
Changes: Add a StaticAppBar component and use that on all routes
Surge Deployment Link: [Add here the link where you changes can be seen]

Fiixes #243: Same AppBar component for all routes

---

src/components/StaticAppBar/StaticAppBar.js

Fixes #255 
Changes: 
- Correct position for DropDown menu.
- Speed up animation like on chat.susi.ai
Surge Deployment Link: http://fair-mailbox.surge.sh/

Correct position for DropDown menu and speed up animation similar to chat.susi

---

src/components/Auth/SignUp/SignUp.css
src/components/Footer/Footer.css

Fixes #259 
Changes: 
- Implement same footer alignment as of chat.susi
- Implement different color for about section
Surge Deployment Link: http://wooden-paint.surge.sh/
before
now

Implement same footer alignment same as chat.susi and minor changes

---

src/components/Auth/LoggedIn/LoggedIn.css
src/components/Auth/LoggedIn/LoggedIn.react.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #261 
Changes: 
- Fix bug for welcome message 
- Display email of logged in user on top bar
Surge Deployment Link: http://jaded-hair.surge.sh/

Correct bug of welcome message and display email of loggedIn user on top bar

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.react.js

Fixes #244 
Changes: 
- Implement new UI for login page
- Add smoothness to input fields
Note: PR #260 needs to be merged first
Surge Deployment Link: http://childlike-cow.surge.sh

Implement new login page and add smoothness to input fields

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js

Fixes #269 
Changes: Implement similar input fields as of password tab of chat.susi 
Surge Deployment Link: http://hissing-dog.surge.sh/

Implement similar input field for login page as of password tab of chat.susi

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Changes: 
- Implement new UI
- Add responsiveness for mobile view
Surge Deployment Link: http://ruthless-spiders.surge.sh/
for smaller size and mobile view

Implement new UI for settings page similar to chat.susi settings

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.css

Fixes #273 
Changes: 
- Improve UI for start page
- Login section comes first before about section.
Surge Deployment Link: http://young-drum.surge.sh/

Improve Start Page UI for mobile view

---

src/components/StaticAppBar/StaticAppBar.js

Fixes #276 
Changes:
- Added "Dashboard" to the top.
- "About" is on the bottom just above login/logout.
Surge Deployment Link: http://dependent-wall.surge.sh/
Not logged in:
Logged in:

Rearrange hamburger menu

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.css
src/components/StaticAppBar/StaticAppBar.js

Fixes #264 
Changes: Add animation for top bar to disappear on scroll
Surge Deployment Link: http://secret-taste.surge.sh/
NA

Add animation to top bar

---

src/components/Auth/Logout.react.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #280 
Changes: Display username when available
Surge Deployment Link: https://bawdy-grape.surge.sh

Fixes #280: Display username on appbar if available

---

src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #266 
Changes: 
- Add all settings of webclient
- Removed Change Password option from hamberger menu
- Add Change password tab in settings page itself
- Add icons for all tabs
- Implement Similar UI as of chat.susi settings
- Implement grey background
Surge Deployment Link: http://squeamish-size.surge.sh/

Add all webclient settings and improved UI for settings page

---

src/actions/API.actions.js
src/actions/Settings.actions.js
src/components/Settings/Settings.react.js

Fixes #284 
Changes: Implement save changes to server
Surge Deployment Link: https://pr-286-fossasia-susi-accounts.surge.sh
NA

Implement save changes to server

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #285 
Changes: 
- Link susi logo to home
- Fix background issue during animation
- Fix shadow issue with password tab
Surge Deployment Link: https://pr-288-fossasia-susi-accounts.surge.sh

Fix background issue with top bar and minor fixes

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Settings/Settings.css

Fixes #244 
Changes: 
- Fix responsiveness issues of login page
- Remove indents from input fields
Surge Deployment Link: https://pr-289-fossasia-susi-accounts.surge.sh

Fix issues with responsiveness of start page

---

package.json

Fixes #294 
Changes: Run code formatting before checking eslint config.
Surge Deployment Link: https://pr-295-fossasia-susi-accounts.surge.sh
NA

Fixes #294: Tune lint-staged to first format code and then run eslint checks

---

src/components/Settings/Settings.react.js

Fixes #290 
Changes: 
- Fix bug with country code that earlier country code was always US despite the value on server
- Implement UI of mobile tab similar to chat.susi and correct position
Surge Deployment Link: https://pr-298-fossasia-susi-accounts.surge.sh

Implement UI of mobile tab similar to chat.susi and correct position and fix bug with country code

---

.travis.yml

Fixes #300 
* Upgrade node_js version in travis.yml
Surge Deployment Link: https://pr-301-fossasia-susi-accounts.surge.sh
NA

Fixes #300: Upgrade node_js version on .travis.yml

---

public/index.html

Fixes #309 
* Correct website title
* Correct SEO tags
Surge Deployment Link: https://pr-310-fossasia-susi-accounts.surge.sh

Fixes #309: Correct the website title and SEO data

---

src/components/Settings/Settings.react.js

Fixes #304 
Changes: Now clicking on the icons for each tab displays the corresponding section on the right side.
Surge Deployment Link: https://pr-313-fossasia-susi-accounts.surge.sh

Fixed issues with clicking of icons in settings

---

src/components/Admin/ListUser/ListUser.js

Fixes #302 
Changes: Implement feature to change roles of users
Surge Deployment Link: https://pr-307-fossasia-susi-accounts.surge.sh
Click edit to open edit dialog box
If changes are successful , this message appears

Implement change roles feature on admin page

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js

Fixes #317 
Changes: Add confirmation message before deleting account
Surge Deployment Link: https://pr-318-fossasia-susi-accounts.surge.sh

Add confirmation message for delete account

---

src/components/Footer/Footer.react.js

Fixes #326 
Changes: Add API to footer
Surge Deployment Link: https://pr-327-fossasia-susi-accounts.surge.sh

Fixes #326: Add API to footer

---

src/actions/API.actions.js
src/actions/index.js
src/components/Settings/Settings.react.js

Fixes #338 
* Remove the errors that were thrown.
Surge Deployment Link: https://pr-339-fossasia-susi-accounts.surge.sh

Fixes #338: Fix bugs while saving settings

---

src/components/Admin/ListUser/ListUser.js

Fixes #343
Changes: Used newly implemented user roles in Users tab in Admin panel.
Surge Deployment Link: https://pr-346-fossasia-susi-accounts.surge.sh

Used newly implemented user roles in Users tab in Admin panel

---

src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Footer/Footer.css
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #347 
Changes: 
- Add some filters for tables on users and skills tab
- Fix issue with user role change message
- Make English as default language for ant design components
- Refractor css to use ant design css instead of custom css for different ant design components to avoid UI bugs
Surge Deployment Link: https://pr-348-fossasia-susi-accounts.surge.sh

Implement filters on tables and minor fixes

---

src/actions/API.actions.js
src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/components/Footer/Footer.react.js
src/components/NotFound/NotFound.react.js
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js
src/stores/UserPreferencesStore.js
src/utils/urls.js

Fixes #356 
Changes: Use urls from a config file
Surge Deployment Link: https://pr-362-fossasia-susi-accounts.surge.sh
NA

Fixes #356: Use urls throughout the app from a config file

---

src/components/Admin/Admin.js

Fixes #333 
Changes: Implement user stats on admin page
Surge Deployment Link: https://pr-370-fossasia-susi-accounts.surge.sh

Implement user stats on admin page

---

src/components/Admin/ListSkills/ListSkills.js

Fixes #331 
Fixed #354 
Changes: 
- Implement delete Skills feature
- Implement restore Skills feature
- Implement Dynamic filters for groups
Surge Deployment Link: https://pr-360-fossasia-susi-accounts.surge.sh

Implement Delete skill feature

---

src/index.js

Fixes #373 
* Remove duplicate declaration of /settings route
Surge Deployment Link: https://pr-375-fossasia-susi-accounts.surge.sh

Fixes #373: Remove duplicate declaration of /settings route

---

src/components/Admin/ListUser/ListUser.js

Fixes #344 
Changes: Implement search feature on users tab
Surge Deployment Link: https://pr-381-fossasia-susi-accounts.surge.sh

Implement search users feature

---

src/components/Admin/Admin.css
src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Admin/SystemSettings/SystemSettings.js
src/index.js

Fixes #324 
Changes: Display API keys on admin panel
Surge Deployment Link: https://pr-396-fossasia-susi-accounts.surge.sh

Display API keys on admin panel

---

src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/components/NotFound/NotFound.react.js
src/components/Settings/Settings.react.js
src/components/Settings/WebChat/WebchatSettings.react.js
src/components/StaticAppBar/StaticAppBar.js
src/constants/ChatConstants.js

Fixes #368 
Changes: Used standard blue color for all dialog boxes in Admin Panel.
Surge Deployment Link: https://pr-397-fossasia-susi-accounts.surge.sh

Used standard blue color for all dialog boxes in Admin Panel

---

src/config.js

Fixes #324 
Changes: Fetch API keys from server instead of hard coding
Surge Deployment Link: https://pr-403-fossasia-susi-accounts.surge.sh
NA

Fetch API keys from server

---

src/actions/API.actions.js
src/components/Admin/Admin.js
src/components/Admin/ListUser/ListUser.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Auth/VerifyAccount/VerifyAccount.react.js
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js
src/stores/UserPreferencesStore.js

Fixes #409 
Changes: Removed unnecessary console logs
Surge Deployment Link: https://pr-410-fossasia-susi-accounts.surge.sh

Removed unnecessary console logs

---

src/components/Admin/ListUser/ListUser.js

Fixes #411 
Changes: Minor punctuation fix in the message in the delete user dialog
Surge Deployment Link: https://pr-412-fossasia-susi-accounts.surge.sh

Minor punctuation fix in the message in the delete user dialog

---

src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js

Fixes #379 
Fixes #401  
Changes: 
- Implement loader on users tab
- Fix width issue with columns of users table
- Change empty table label from 'no data' to 'no users found'
Surge Deployment Link: https://pr-402-fossasia-susi-accounts.surge.sh

Minor improvements for users tab

---

src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Settings/Settings.css

Fixes #418 
Changes: Add jumpers to tables
Surge Deployment Link: https://pr-419-fossasia-susi-accounts.surge.sh

Add jumpers to tables

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js

Fixes #421 
Changes: Much cleaner delete account component, compare it with the screenshot in the issue.
Surge Deployment Link: https://pr-427-fossasia-susi-accounts.surge.sh

Fixes #421: Much cleaner delete account component

---

src/components/Admin/ListSkills/ListSkills.js

Fixes #414 
Changes: Added null checks in `ListSkills.js`
Corresponding PR on CMS: https://github.com/fossasia/susi_skill_cms/pull/1452
Surge Deployment Link: https://pr-428-fossasia-susi-accounts.surge.sh

Added null checks in ListSkills.js

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.css
src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/ResetPassword/ResetPassword.css
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/VerifyAccount/VerifyAccount.css
src/components/Settings/Settings.react.js

Fixes #357 
Changes: Fixed topbar.
Surge Deployment Link: https://pr-415-fossasia-susi-accounts.surge.sh
After commit:
Before commit:

Fixed topbar

---

src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js

Fixes #431 
Changes: Fixed all minor grammatical issues in Admin Panel
Surge Deployment Link: https://pr-432-fossasia-susi-accounts.surge.sh

Fixed all minor grammatical issues in Admin Panel

---

src/components/Auth/ForgotPassword/ForgotPassword.css
src/components/Auth/ForgotPassword/ForgotPassword.react.js

Fixes #425 
Changes: Quick fix for buttons alignment.
Surge Deployment Link: https://pr-426-fossasia-susi-accounts.surge.sh

Fixes #425: Fix buttons alignment in forgotpassword component

---

src/components/Admin/ListUser/ListUser.js

Fixes #391 
Changes: Add fuctionality to change device config on users tab
Surge Deployment Link: https://pr-436-fossasia-susi-accounts.surge.sh

Add fuctionality to change device config on users tab

---

src/components/Settings/Settings.react.js

Fixes #377 
Changes: Add validation to mobile number similar to chat.susi
Chat PR : https://github.com/fossasia/chat.susi.ai/pull/1435
Surge Deployment Link: https://pr-417-fossasia-susi-accounts.surge.sh

Add validation to mobile number

---

src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Admin/SystemLogs/SystemLogs.js
src/components/Admin/SystemSettings/SystemSettings.js
src/index.js

Fixes #407 
Changes: 
- Implement system logs with count filter
- Show success div if the logs are free from error
- Show error div if the logs contain errors
Surge Deployment Link: https://pr-437-fossasia-susi-accounts.surge.sh

Implement system logs

---

src/components/Admin/ListSkills/ListSkills.js

Fixes #440 
Changes: Fixed issues with switching to `System Settings` tab from `Skills` tab in Admin Panel
Surge Deployment Link: https://pr-442-fossasia-susi-accounts.surge.sh

Fixed issues with switching to System Settings tab in Admin Panel

---

package.json

Fixes #444 
Changes: Add missing fields in package.json
Surge Deployment Link: https://pr-445-fossasia-susi-accounts.surge.sh
NA

Fixes #444: Add missing fields in package.json

---

src/__tests__/components/Admin/Admin.js
src/__tests__/components/Admin/ListSkills/ListSkills.js
src/__tests__/components/Admin/ListUser/ListUser.js
src/__tests__/components/Admin/SystemLogs/SystemLogs.js
src/__tests__/components/Admin/SystemSettings/SystemSettings.js
src/__tests__/components/Auth/ChangePassword/ChangePassword.js
src/__tests__/components/Auth/DeleteAccount/DeleteAccount.js
src/__tests__/components/Auth/ForgotPassword/ForgotPassword.js
src/__tests__/components/Auth/Login/Login.js
src/__tests__/components/Auth/Logout.js
src/__tests__/components/Auth/ResetPassword/ResetPassword.js
src/__tests__/components/Auth/SignUp/SignUp.js
src/__tests__/components/Auth/VerifyAccount/VerifyAccount.js
src/__tests__/components/CircleImage/CircleImage.js
src/__tests__/components/Footer/Footer.react.js
src/__tests__/components/MapContainer/MapContainer.react.js
src/__tests__/components/NotFound/NotFound.react.js
src/__tests__/components/Settings/Settings.react.js
src/__tests__/components/Settings/WebChat/WebchatSettings.react.js
src/__tests__/components/StaticAppBar/StaticAppBar.js
src/__tests__/components/TableComplex/RemoveDeviceDialog.react.js
src/__tests__/components/TableComplex/TableComplex.react.js
src/components/CircleImage/CircleImage.js

Fixes #449 
Changes: Added rendering tests for all components
Surge Deployment Link: https://pr-450-fossasia-susi-accounts.surge.sh

Added rendering tests for all components

---

src/components/Admin/SystemLogs/SystemLogs.js

Fixes #451 
Changes: Implement dropdown for log count
Surge Deployment Link: https://pr-452-fossasia-susi-accounts.surge.sh

Implement dropdown for log count

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js
src/stores/UserPreferencesStore.js

Ref #399 
Changes: 
* Implemented add upload avatar feature
Dependent on https://github.com/fossasia/susi_server/pull/1144
Surge Deployment Link: https://pr-456-fossasia-susi-accounts.surge.sh

Ref #399: Add upload avatar feature

---

src/components/StaticAppBar/StaticAppBar.js

Fixes #460 
Changes:
* Integrate /getAvatar.png API
Surge Deployment Link: https://pr-465-fossasia-susi-accounts.surge.sh

Fixes #460: Integrate /getAvatar.png API

---

src/components/Auth/Login/Login.react.js

Fixes #467 
Changes: 
* Added padding to the input fields of the login form on the home page.
Surge Deployment Link: https://pr-467-fossasia-susi-accounts.surge.sh/

Fixes #467 : Add padding to Login input fields

---

package.json

Fixes #435 
Changes: 
* Added breaking dependencies
Surge Deployment Link: https://pr-466-fossasia-susi-accounts.surge.sh

Fixes #435: Fix error on npm start

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #469 
Changes: 
- Improve Signup page input fields border style.
- Add spacing between text and input fields.
Surge Deployment Link: https://pr-470-fossasia-susi-accounts.surge.sh
@anshumanv @arundhati24 @PrP-11, Please review this PR.

Fixes #469 - Improve the styling of Signup page

---

package.json
src/components/Auth/Login/Login.css
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #469 
fixed the layout of the signup page. And also the styling as well.
Deployed at [surge here](https://skillful-war.surge.sh)
This PR is new one of the earlier already reviewed PR #359 . @DNS-404 recommended me to make a new PR.
@PrP-11 , @anshumanv , @AnupKumarPanwar please Review

signup page layout and squeezed fixed

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js

Fixes #484 
Changes: Aligned Forgot password link with password, change size
Surge Deployment Link: https://pr-484-fossasia-susi-accounts.surge.sh

Forgot Password Link UI Fix #484

---

src/components/Auth/ForgotPassword/ForgotPassword.css
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Footer/Footer.react.js

Fixes #416 
Changes: Added footer and some changes
Surge Deployment Link: https://pr-473-fossasia-susi-accounts.surge.sh

Redesign Forgot Password Change #416

---

src/components/Footer/Footer.css

Fixes #491
Changes: SUSI logo is now aligned with other footer elements
Surge Deployment Link: https://pr-492-fossasia-susi-accounts.surge.sh

SUSI logo aligned in footer

---

src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #489
Changes: When screen size of sign up page is decreased the elements are arranged properly .
Surge Deployment Link: https://pr-490-fossasia-susi-accounts.surge.sh

Added responsive design for SignUp page

---

src/components/Auth/Login/Login.css
src/components/Auth/SignUp/SignUp.css

Fixes #493 
Changes: CSS property in About class of Login Page and Signup page is corrected
Surge Deployment Link: https://pr-494-fossasia-susi-accounts.surge.sh

Property name corrected

---

src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #499 
Changes: Fixed the forgot password link in Passwords tab of Settings page
Surge Deployment Link: https://pr-500-fossasia-susi-accounts.surge.sh
@anshumanv @akshatnitd @Akshat-Jain @DNS-404  Please review.
Thanks!

Fixed forgot password link

---

src/components/StaticAppBar/StaticAppBar.js

Fixes #501
Now avatar remains fixed unless we refresh the page.
Surge Deployment Link: https://pr-504-fossasia-susi-accounts.surge.sh
ping @anshumanv @mariobehling

Fixed re-rendering of avatar

---

src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #482 
Changes: 
Some UI Tweaks for sign up page
- Fixed font-size
- Spacing of text
- Minor details can be seen in screenshot
Surge Deployment Link: https://pr-482-fossasia-susi-accounts.surge.sh

UI Tweaks For Sign Up Page#482

---

src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js

Fixes #510
Due to some confusion for PR https://github.com/fossasia/accounts.susi.ai/pull/479, new 2 PR created
Changes: 
- Placeholder
- Fix Position
- Some orientation changes
Surge Deployment Link: https://pr-510-fossasia-susi-accounts.surge.sh
**New**
**Old**

UI tweaks for Password in Settings#510

---

src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/SignUp.css

Fixes #497 
Changes: When login page width is decreased, the responsive design works fine now.
- Added a media query to handle the squeeze.
Surge Deployment Link: https://pr-498-fossasia-susi-accounts.surge.sh
@anshumanv @akshatnitd @Akshat-Jain @DNS-404  please review.
Thanks!

Fixed Responsive Design of Login Page

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #505 
Changes: 
account deactivation link's alignment fixed
Surge Deployment Link: https://pr-507-fossasia-susi-accounts.surge.sh

account deactivation link's alignment fixed

---

src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/components/Admin/SystemLogs/SystemLogs.js
src/components/Admin/SystemSettings/SystemSettings.js

Fixes #521 
Changes: Fixes warning, reduces size
Surge Deployment Link: https://pr-521-fossasia-susi-accounts.surge.sh
Updated link: mean-arch.surge.sh

Modular Imports to reduce size, fix warning#521

---

src/config.js

Fixes #519
Changes: ajax call in config function is changed to asyc: true
Surge Deployment Link: https://pr-519-fossasia-susi-accounts.surge.sh

Fix XHR Warning #519

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #530 
Changes: Radio button alignment in ChatApp and Microphone settings is now correct when screen width is reduced.
Surge Deployment Link: https://pr-535-fossasia-susi-accounts.surge.sh

Radio button alignment fixed in Settings

---

src/components/Settings/Settings.react.js

Fixes #538
Changes: Fix bug when avatar type is changed from the drop-down menu.
Surge Deployment Link: https://pr-538-fossasia-susi-accounts.surge.sh

Fix Avatar Change Drop Menu #538

---

src/components/Admin/Admin.js

Fixes #560 
Changes: There are 7 Fix cannot read property errors in Admin section.
Surge Deployment Link: https://pr-560-fossasia-susi-accounts.surge.sh
See PR for more details.

Fix cannot read property in Admin.js#560

---

src/components/Admin/ListSkills/ListSkills.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/Login/Login.react.js

Fixes #558 
Changes: Use arrow function(ES6) instead of manually binding it.
Surge Deployment Link: https://pr-558-fossasia-susi-accounts.surge.sh

Use arrow fn instead of explicit Bind #558

---

src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/Logout.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Settings/PreviewThemeChat.js
src/components/Settings/Settings.react.js
src/components/Settings/ThemeChanger.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #564 
Changes: Uses let and const instead of var.
Demo Link: https://pr-564-fossasia-susi-accounts.surge.sh

Use let, const instead of var#564

---

src/components/Admin/Admin.js
src/components/Admin/ListSkills/ListSkills.js
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/Login/Login.react.js
src/components/Auth/Logout.react.js
src/components/Auth/ResetPassword/ResetPassword.react.js
src/components/Settings/PreviewThemeChat.js
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js
src/components/Settings/ThemeChanger.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #548 
Changes: 
* Reset password validation code made better
* If there is an error in one field, and we start typing in other field, the error in the previous field is displayed.
* After making the 'New Password' and 'Confirm Password' fields equal, if we make any changes in 'New Password', the confirm password error of unequal passwords is shown.
Surge Deployment Link: https://pr-549-fossasia-susi-accounts.surge.sh

Reset password validation code improved

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #546 
Changes: When screen size is changed then the width of each textarea is same.
Surge Deployment Link: https://pr-550-fossasia-susi-accounts.surge.sh

Width of the textarea is consistent when screen size is changed

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #591 
Changes: The changes I have made are as follows:
Surge Deployment Link: https://pr-592-fossasia-susi-accounts.surge.sh

Fixes  #591: Loader size fixed, redundant code removed

---

src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #544 
Changes: While entering the password on signup page the password strength is shown.
Surge Deployment Link: https://pr-555-fossasia-susi-accounts.surge.sh

Password strength added on signup page

---

src/components/Auth/VerifyAccount/VerifyAccount.react.js

Fixes #[609](https://github.com/fossasia/accounts.susi.ai/issues/609#issue-389746279)

Added space after punctuation mark

---

src/components/Footer/Footer.css
src/components/Footer/Footer.react.js
src/components/Settings/Settings.react.js

Fixes #621 
Changes: Currently the footer is not responsive and consistent with other similar pages like skills.susi.ai. But it should be responsive and consistent.
Surge Deployment Link: https://pr-622-fossasia-susi-accounts.surge.sh

Make footer consistent and responsive

---

src/components/Settings/Settings.react.js

Fixes #616 
Changes: Changed the term "Deactivate" to "Delete"
Surge Deployment Link: https://pr-617-fossasia-susi-accounts.surge.sh

Fixed the terminology

---

docs/Accounting.md

Updated Accounting.md
Fixes #[630](https://github.com/fossasia/accounts.susi.ai/issues/630)
Changes: Added Change Password field in Accounting.md

Updated Accounting.md

---

src/components/Auth/Logout.react.js
src/components/CircleImage/CircleImage.js
src/components/Footer/Footer.react.js

Fixes #572 
Changes: Following components are made functional:
- Logout
- CircleImage
- Footer
Surge Deployment Link: https://pr-572-fossasia-susi-accounts.surge.sh

Make stateless components into functional components #572

---

src/__tests__/components/Auth/SignUp/Description.js
src/components/Auth/Login/Login.css
src/components/Auth/Login/Login.react.js
src/components/Auth/SignUp/Description.js
src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #643 
Changes: 
- Added styling
- Added Learn More button on the left side
- Made the section responsive
- Made left side with "Meet SUSI.AI, Your Artificial Intelligence for Personal Assistants, Robots, Help Desks and Chatbots." a separate functional component, used in homepage and sign up page
Surge Deployment Link: https://pr-644-1-fossasia-susi-accounts.surge.sh
Home page before:
Home page After:

Redesign Home page for Accounts SUSI #643

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #529 
Changes: On using timezone dropdown the button and link don't shift downwards
Surge Deployment Link: https://pr-636-fossasia-susi-accounts.surge.sh

Fixed the timezone CSS bug

---

src/components/Auth/Login/Login.react.js

Fixes #657 
Changes: Currently when user presses login, it shows the logged in message but does not log you in on the first time. But, it should log in on the first time.
Surge Deployment Link: https://pr-659-fossasia-susi-accounts.surge.sh

fix first time login issue

---

src/components/Settings/ThemeChanger.js

Fixes #590
Changes: The changes I have made are:
Surge Deployment Link: https://pr-593-fossasia-susi-accounts.surge.sh
Let me know if I missed anything.

Fixes #590: ThemeChanger.js refactored

---

README.md

Fixed errors in Readme

---

src/components/MapContainer/MapContainer.react.js

Fixes #677 
Changes: The changes I have made are as follows:
Surge Deployment Link: https://pr-678-fossasia-susi-accounts.surge.sh

Fixes 677: MapContainer refactored

---

src/components/Footer/Footer.css
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #673 
Changes: Currently the position of footer is not consistent. But, it should be consistent.
Surge Deployment Link: https://pr-683-fossasia-susi-accounts.surge.sh

fix inconsistency in footer position

---

docs/Accounting.md

Rectified punctuation mistakes

---

src/components/ProtectedRoute/ProtectedRoute.js
src/index.js

Fixes #618 
Due to some merge conflits I am closing the previous PR #619 
Changes: 1) Setting Route is now protected, only logged in user can access it.
Surge Deployment Link: https://pr-671-fossasia-susi-accounts.surge.sh

Setting route is protected now

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #637
Changes: Signup route is now not accessible to logged in users.
Surge Deployment Link: https://pr-690-fossasia-susi-accounts.surge.sh

Signup Route is not accessible to logged In users

---

src/components/TableComplex/RemoveDeviceDialog.react.js
src/components/TableComplex/TableComplex.react.js

Fixes #675
Changes:  The changes I have made are:
Surge Deployment Link: https://pr-676-fossasia-susi-accounts.surge.sh

Fixes #675: TableComplex components refactored

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #551 
Changes: If there is an error in one field on signup page, and we start typing in other field, the error in the previous field will also be displayed.
Surge Deployment Link: https://pr-552-fossasia-susi-accounts.surge.sh

Improved form validation on signup page

---

src/components/Auth/ChangePassword/ChangePassword.css
src/components/Auth/ChangePassword/ChangePassword.react.js
src/components/Settings/ThemeChanger.css

Fixes #545 
Changes: While entering the password in the settings page(changing password) the password strength is shown.
Surge Deployment Link: https://pr-557-fossasia-susi-accounts.surge.sh

Password strength while changing password

---

src/components/Settings/ThemeChanger.js

Fixes #566 
Changes: Scrollbar is removed
Surge Deployment Link: https://pr-567-fossasia-susi-accounts.surge.sh

Removed scroll bar

---

src/components/Auth/Login/Login.react.js

Fixes #578 
Changes: When both email and password field are valid then only login button should be enabled.
Surge Deployment Link: https://pr-579-fossasia-susi-accounts.surge.sh

Proper form validation in login page

---

src/components/Auth/ResetPassword/ResetPassword.react.js

Fixes #626 
Changes: Correct error message is displayed when someone visits reset password route.
Surge Deployment Link: https://pr-629-fossasia-susi-accounts.surge.sh

Error message corrected

---

src/components/Auth/SignUp/SignUp.react.js
src/components/Auth/SignUp/SignupMobileFix.min.css

Fixes #645 
Changes:
The signup form is not responsive for the mobile screen. Try to signup in small screens.
Surge Deployment Link: https://pr-646-fossasia-susi-accounts.surge.sh

FIx Signup In Mobile View

---

src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #653 
Changes: Provide padding between the elements in the settings page. Corrected responsiveness.
Surge Deployment Link: https://pr-654-fossasia-susi-accounts.surge.sh

Corrected padding and responsive in the settings page

---

src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Auth/ForgotPassword/ForgotPassword.react.js
src/components/Auth/Login/Login.react.js
src/components/CircleImage/CircleImage.js
src/components/Settings/PreviewThemeChat.js
src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js

Removed unwanted console.logs
Fixes [#640 #674] 
Changes: 
- Replaced console.logs with console.error
- Fixed error with unexpected props
Surge Deployment Link: https://pr-679-fossasia-susi-accounts.surge.sh

Fix #640 #674 Fixed issue with warnings  and Console.logs

---

src/__tests__/Utils/Utils.js

Fixes #709
Changes: Added test for Utils.js file.
Surge Deployment Link: https://pr-710-fossasia-susi-accounts.surge.sh

feat(test): Add test for Utils.js

---

.github/PULL_REQUEST_TEMPLATE

Fixes #698
Changes: 
Rectified grammatical issues in the PR template and added details regarding screenshot.

Updated PR Template

---

src/components/Settings/Settings.react.js

Fixes #595 
Changes: The changes I propose are:
Surge Deployment Link: https://pr-596-fossasia-susi-accounts.surge.sh

Fixes #595: Settings.react.js refactored

---

src/components/Auth/DeleteAccount/DeleteAccount.css
src/components/Auth/DeleteAccount/DeleteAccount.react.js
src/components/Settings/Settings.css
src/components/Settings/Settings.react.js

Fixes #685 
Changes: 
Surge Deployment Link: https://pr-688-fossasia-susi-accounts.surge.sh

modify ui for delete account

---

src/__tests__/Utils/isEmailTest.js

Fixes #711
Changes: Added test for checking Email regex.
Surge Deployment Link: https://pr-712-fossasia-susi-accounts.surge.sh

feat(test): Add test for checking email regex

---

src/components/Settings/Settings.css

Fixes #715 
Changes: No scroll bar is present now.
Surge Deployment Link: https://pr-716-fossasia-susi-accounts.surge.sh
Screenshots for the change: ![capture](https://user-images.githubusercontent.com/28510494/52779092-81471a80-306d-11e9-9eb7-94d43a999407.PNG)

Fixed avatar dropdown CSS issue

---

src/components/Auth/SignUp/SignUp.react.js

Fixes #642 
Surge Deployment Link: https://pr-713-fossasia-susi-accounts.surge.sh

Trim whitespace from ends of password

---

src/components/Settings/Settings.react.js
src/components/StaticAppBar/StaticAppBar.js

Fixes #707
Changes: Fixed console errors for can not <property> of undefined. 
Surge Deployment Link: https://pr-708-fossasia-susi-accounts.surge.sh

Fix console error on accounts.susi.ai/settings page

---

src/__tests__/components/ProtectedRoute/ProtectedRoute.js

Fixes #701 
Changes: Added Test for Protected Route
Surge Deployment Link: https://pr-702-fossasia-susi-accounts.surge.sh

Added test for Protected Route

---

src/components/Auth/ForgotPassword/ForgotPassword.react.js

Fixes #727 
Changes: Clear Email Field in Forgot Password when clicked on Cancel Button
Surge Deployment Link: https://pr-728-fossasia-susi-accounts.surge.sh

Clear Email Field in Forgot Password when clicked on Cancel Button

---

src/components/Admin/ListSkills/ListSkills.js
src/components/Admin/ListUser/ListUser.js
src/constants/ChatConstants.js

Fixes #730 
Changes: Change colour of delete button to red in Admin panel
Surge Deployment Link: https://pr-731-fossasia-susi-accounts.surge.sh

Change colour of delete button to red in Admin panel

---

src/actions/API.actions.js
src/components/Settings/Settings.react.js

Fixes #743 
Changes: 
Display snackbar on setting change
Surge Deployment Link: https://pr-744-fossasia-susi-accounts.surge.sh

Display snackbar on setting change

---

src/components/Auth/SignUp/SignUp.css
src/components/Auth/SignUp/SignUp.react.js

Fixes #751 
Changes: Center aligned password strength and fix UI of signup form in mobile view.
Surge Deployment Link: https://pr-752-fossasia-susi-accounts.surge.sh

Center align the password strength in Sign up form and fix mobile UI of Signup form

---

README.md

Correct Surge link in README

---

src/components/Auth/Login/Login.css

Fixes #740 
Changes: Added some space between link div and learn more
Surge Deployment Link: https://pr-759-fossasia-susi-accounts.surge.sh

added space between learn more and login div
